apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: demos-0001
build:
  artifacts:
    - image: bhuwanupadhyay/service-0001
      jib:
        project: ./
        args:
          - -Pjib
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml